# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory extendedglob nomatch notify
unsetopt autocd beep
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/yuri/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
export XDG_CURRENT_DESKTOP='Unity slack'
export _JAVA_AWT_WM_NONREPARENTING='1'
export QT_WAYLAND_DISABLE_WINDOWDECORATION='1'
export QT_QPA_PLATFORMTHEME="qt5ct"
/usr/bin/pfetch
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
